#!/usr/bin/perl -w
use strict;
use warnings;
use lib 'BookmakerOfferDownloader/';
use BetExplorerDownloader;


#SUBS DECLARATIONS
sub parseArguments();
sub printUsage();
sub printManual();
sub checkRunMode();
sub findSureBets($$);


###########MAIN#############
if( parseArguments() )
{
	my $runMode = checkRunMode();

	if($runMode eq 'SHOW_MANUAL_MODE')
	{
		printManual();
	}
	elsif($runMode eq 'FIND_SUREBET_MODE')
	{
		my $xmlSelectorFile = $ARGV[0];
		my $xmlResultFile = $ARGV[1];
		findSureBets($xmlSelectorFile, $xmlResultFile);
	}	
}
else
{
	printUsage();
}



#########SUBS DEFINITIONS##############
sub parseArguments()
{
	if ($#ARGV == -1)
	{
		return 0;
	}
	
	my $allProgramArguments = join(' ',@ARGV);
	
	if ($allProgramArguments =~ /^([\w\\\.]+) ([\w\\\.]+)$/)
	{
		return 1;
	}
	
	if ($allProgramArguments =~ /^--help$/)
	{
		return 2;
	}
	
	return 0;
	
	

};


sub printManual()
{

	open my $fh_manual , "<", "design/manual.txt" or die; 

	{
		local $/ = undef;
		print <$fh_manual>;
	}
	
	close $fh_manual or die;

}

sub printUsage()
{
	open my $fh_usageFile , "<", "design/usage.txt" or die;
	{
		local $/ = undef;
		print <$fh_usageFile>;
	}
	
	close $$fh_usageFile or die;
		
}

sub checkRunMode()
{
	if($#ARGV == 0)
	{
		return 'SHOW_MANUAL_MODE' 
	}
	elsif($#ARGV == 1)
	{
		return 'FIND_SUREBET_MODE'
	}

	die;
};

sub findSureBets($$)
{
	
	my ($xmlSelectorFile , $xmlResultFile) = @_;
	my $theRealBookMakerDownloader =  BetExplorerDownloader->new('--realnet');
	$theRealBookMakerDownloader->loadSelectorFile($xmlSelectorFile); #temporary moved before "BookMakerDownloader->createEventListXML"
	
	$theRealBookMakerDownloader->pullBookmakersOffer($xmlResultFile);
	
	die "NOT IMPLEMENTED YET";

};
